on:
  push:
    branches:
      - main
name: 🚀 Deploy Website on Push (SCP)
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: 🔐 Sync Core (kopetcodeigniter)
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        port: 65002
        source: "masterprogram_ci4/**,!masterprogram_ci4/vendor/**,!masterprogram_ci4/system/**"
        target: "kopetcodeigniter"
        strip_components: 1

    - name: 🌐 Sync Public (Subdomain)
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        port: 65002
        source: "*,!masterprogram_ci4"
        target: "public_html/waskitho.suaramadiun.com/"
