on:
  push:
    branches:
      - main
name: 🚀 Deploy Website on Push (SFTP v3)
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: 🔐 Sync Core (kopetcodeigniter)
      uses: wangyucode/sftp-upload-action@v3
      with:
        host: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 65002
        localDir: 'masterprogram_ci4'
        remoteDir: 'kopetcodeigniter'
        exclude: '.git/*, .env, vendor/**, system/**'

    - name: 🌐 Sync Public (Subdomain)
      uses: wangyucode/sftp-upload-action@v3
      with:
        host: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 65002
        localDir: './'
        remoteDir: 'public_html/waskitho.suaramadiun.com/'
        exclude: '.git/*, .env, masterprogram_ci4/**'
