on:
  push:
    branches:
      - main
name: 🚀 Deploy Website on Push (SFTP)
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: 🔐 Sync Core (kopetcodeigniter)
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: 65002
        local_path: masterprogram_ci4/
        remote_path: kopetcodeigniter/
        delete_remote_files: false
        exclude: |
          **/.git*
          **/.git*/**
          .env
          vendor/**
          system/**

    - name: 🌐 Sync Public (Subdomain)
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: 65002
        local_path: ./
        remote_path: public_html/waskitho.suaramadiun.com/
        delete_remote_files: false
        exclude: |
          **/.git*
          **/.git*/**
          masterprogram_ci4/**
          .env
